### ISSUE TITLE
チェックリスト画面の表示が遅い

### ISSUE THREAD

**Issue by nobas13** [celeron1ghz/p5-Hirukara-Lite#14]
現状データベースの中に、過去のデータ(C86)のデータかあるため、処理が遅い状況がある
これを削除もしくは退避することで、処理速度の向上を図りたい

**Comment by celeron1ghz** [comment]
fixed in cdc24f0a15b824ed84930eca00fea8daa82635ea

デフォルトで全てを表示しているために遅いので、メニューのリンクを自分のチェックリストのみを表示するように変更。
